version: "3.9"

services:
  cargo-build:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: cargo build --release
    volumes:
      - .:/app
      - rustuser-home:/home/rustuser

  build-summa-wasm:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/summa-wasm
    command: bash build.sh
    volumes:
      - .:/app
      - rustuser-home:/home/rustuser

volumes:
  rustuser-home:
