# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import summa_pb2 as summa__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in summa_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class SearchServiceStub:
    """Search service"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
            "/summa.SearchService/Search",
            request_serializer=summa__pb2.SearchRequest.SerializeToString,
            response_deserializer=summa__pb2.SearchResponse.FromString,
            _registered_method=True,
        )
        self.GetDocument = channel.unary_unary(
            "/summa.SearchService/GetDocument",
            request_serializer=summa__pb2.GetDocumentRequest.SerializeToString,
            response_deserializer=summa__pb2.GetDocumentResponse.FromString,
            _registered_method=True,
        )
        self.GetIndexInfo = channel.unary_unary(
            "/summa.SearchService/GetIndexInfo",
            request_serializer=summa__pb2.GetIndexInfoRequest.SerializeToString,
            response_deserializer=summa__pb2.GetIndexInfoResponse.FromString,
            _registered_method=True,
        )
        self.GetTextStats = channel.unary_unary(
            "/summa.SearchService/GetTextStats",
            request_serializer=summa__pb2.GetTextStatsRequest.SerializeToString,
            response_deserializer=summa__pb2.GetTextStatsResponse.FromString,
            _registered_method=True,
        )


class SearchServiceServicer:
    """Search service"""

    def Search(self, request, context):
        """Search for documents"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetDocument(self, request, context):
        """Get document by ID"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetIndexInfo(self, request, context):
        """Get index info"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTextStats(self, request, context):
        """Text statistics (document frequencies, corpus sizes, average lengths)
        of the BM25 terms of a query over this backend's index. A broker that
        scatters one index over several shards sums the responses and sends the
        total back as `SearchRequest.text_stats`, so every shard scores with
        the same IDF.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Search": grpc.unary_unary_rpc_method_handler(
            servicer.Search,
            request_deserializer=summa__pb2.SearchRequest.FromString,
            response_serializer=summa__pb2.SearchResponse.SerializeToString,
        ),
        "GetDocument": grpc.unary_unary_rpc_method_handler(
            servicer.GetDocument,
            request_deserializer=summa__pb2.GetDocumentRequest.FromString,
            response_serializer=summa__pb2.GetDocumentResponse.SerializeToString,
        ),
        "GetIndexInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetIndexInfo,
            request_deserializer=summa__pb2.GetIndexInfoRequest.FromString,
            response_serializer=summa__pb2.GetIndexInfoResponse.SerializeToString,
        ),
        "GetTextStats": grpc.unary_unary_rpc_method_handler(
            servicer.GetTextStats,
            request_deserializer=summa__pb2.GetTextStatsRequest.FromString,
            response_serializer=summa__pb2.GetTextStatsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "summa.SearchService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("summa.SearchService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class SearchService:
    """Search service"""

    @staticmethod
    def Search(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/summa.SearchService/Search",
            summa__pb2.SearchRequest.SerializeToString,
            summa__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetDocument(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/summa.SearchService/GetDocument",
            summa__pb2.GetDocumentRequest.SerializeToString,
            summa__pb2.GetDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetIndexInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/summa.SearchService/GetIndexInfo",
            summa__pb2.GetIndexInfoRequest.SerializeToString,
            summa__pb2.GetIndexInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTextStats(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/summa.SearchService/GetTextStats",
            summa__pb2.GetTextStatsRequest.SerializeToString,
            summa__pb2.GetTextStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class IndexServiceStub:
    """Index service"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateIndex = channel.unary_unary(
            "/summa.IndexService/CreateIndex",
            request_serializer=summa__pb2.CreateIndexRequest.SerializeToString,
            response_deserializer=summa__pb2.CreateIndexResponse.FromString,
            _registered_method=True,
        )
        self.IndexDocuments = channel.stream_unary(
            "/summa.IndexService/IndexDocuments",
            request_serializer=summa__pb2.IndexDocumentRequest.SerializeToString,
            response_deserializer=summa__pb2.IndexDocumentsResponse.FromString,
            _registered_method=True,
        )
        self.BatchIndexDocuments = channel.unary_unary(
            "/summa.IndexService/BatchIndexDocuments",
            request_serializer=summa__pb2.BatchIndexDocumentsRequest.SerializeToString,
            response_deserializer=summa__pb2.BatchIndexDocumentsResponse.FromString,
            _registered_method=True,
        )
        self.DeleteDocuments = channel.unary_unary(
            "/summa.IndexService/DeleteDocuments",
            request_serializer=summa__pb2.DeleteDocumentsRequest.SerializeToString,
            response_deserializer=summa__pb2.DocumentMutationResponse.FromString,
            _registered_method=True,
        )
        self.UpsertDocuments = channel.unary_unary(
            "/summa.IndexService/UpsertDocuments",
            request_serializer=summa__pb2.UpsertDocumentsRequest.SerializeToString,
            response_deserializer=summa__pb2.DocumentMutationResponse.FromString,
            _registered_method=True,
        )
        self.Commit = channel.unary_unary(
            "/summa.IndexService/Commit",
            request_serializer=summa__pb2.CommitRequest.SerializeToString,
            response_deserializer=summa__pb2.CommitResponse.FromString,
            _registered_method=True,
        )
        self.ForceMerge = channel.unary_unary(
            "/summa.IndexService/ForceMerge",
            request_serializer=summa__pb2.ForceMergeRequest.SerializeToString,
            response_deserializer=summa__pb2.ForceMergeResponse.FromString,
            _registered_method=True,
        )
        self.Reorder = channel.unary_unary(
            "/summa.IndexService/Reorder",
            request_serializer=summa__pb2.ReorderRequest.SerializeToString,
            response_deserializer=summa__pb2.ReorderResponse.FromString,
            _registered_method=True,
        )
        self.DeleteIndex = channel.unary_unary(
            "/summa.IndexService/DeleteIndex",
            request_serializer=summa__pb2.DeleteIndexRequest.SerializeToString,
            response_deserializer=summa__pb2.DeleteIndexResponse.FromString,
            _registered_method=True,
        )
        self.ListIndexes = channel.unary_unary(
            "/summa.IndexService/ListIndexes",
            request_serializer=summa__pb2.ListIndexesRequest.SerializeToString,
            response_deserializer=summa__pb2.ListIndexesResponse.FromString,
            _registered_method=True,
        )
        self.RetrainVectorIndex = channel.unary_unary(
            "/summa.IndexService/RetrainVectorIndex",
            request_serializer=summa__pb2.RetrainVectorIndexRequest.SerializeToString,
            response_deserializer=summa__pb2.RetrainVectorIndexResponse.FromString,
            _registered_method=True,
        )
        self.AlterVectorIndex = channel.unary_unary(
            "/summa.IndexService/AlterVectorIndex",
            request_serializer=summa__pb2.AlterVectorIndexRequest.SerializeToString,
            response_deserializer=summa__pb2.AlterVectorIndexResponse.FromString,
            _registered_method=True,
        )


class IndexServiceServicer:
    """Index service"""

    def CreateIndex(self, request, context):
        """Create a new index (supports both structured schema and SDL string)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def IndexDocuments(self, request_iterator, context):
        """Add documents to index (streaming)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BatchIndexDocuments(self, request, context):
        """Add documents in batch"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteDocuments(self, request, context):
        """Stage whole-document deletions by exact primary key, including every chunk."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpsertDocuments(self, request, context):
        """Stage complete replacements (inserts if absent). Commit publishes them."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Commit(self, request, context):
        """Commit pending changes"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ForceMerge(self, request, context):
        """Force merge segments"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Reorder(self, request, context):
        """Run bounded text, BMP, Seismic, and binary ANN layout maintenance"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteIndex(self, request, context):
        """Delete an index"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListIndexes(self, request, context):
        """List all indexes"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RetrainVectorIndex(self, request, context):
        """Retrain global vector codebooks and atomically rebuild every ANN segment"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AlterVectorIndex(self, request, context):
        """Atomically replace one vector field's IVF/ScaNN algorithm or parameters"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_IndexServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateIndex": grpc.unary_unary_rpc_method_handler(
            servicer.CreateIndex,
            request_deserializer=summa__pb2.CreateIndexRequest.FromString,
            response_serializer=summa__pb2.CreateIndexResponse.SerializeToString,
        ),
        "IndexDocuments": grpc.stream_unary_rpc_method_handler(
            servicer.IndexDocuments,
            request_deserializer=summa__pb2.IndexDocumentRequest.FromString,
            response_serializer=summa__pb2.IndexDocumentsResponse.SerializeToString,
        ),
        "BatchIndexDocuments": grpc.unary_unary_rpc_method_handler(
            servicer.BatchIndexDocuments,
            request_deserializer=summa__pb2.BatchIndexDocumentsRequest.FromString,
            response_serializer=summa__pb2.BatchIndexDocumentsResponse.SerializeToString,
        ),
        "DeleteDocuments": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteDocuments,
            request_deserializer=summa__pb2.DeleteDocumentsRequest.FromString,
            response_serializer=summa__pb2.DocumentMutationResponse.SerializeToString,
        ),
        "UpsertDocuments": grpc.unary_unary_rpc_method_handler(
            servicer.UpsertDocuments,
            request_deserializer=summa__pb2.UpsertDocumentsRequest.FromString,
            response_serializer=summa__pb2.DocumentMutationResponse.SerializeToString,
        ),
        "Commit": grpc.unary_unary_rpc_method_handler(
            servicer.Commit,
            request_deserializer=summa__pb2.CommitRequest.FromString,
            response_serializer=summa__pb2.CommitResponse.SerializeToString,
        ),
        "ForceMerge": grpc.unary_unary_rpc_method_handler(
            servicer.ForceMerge,
            request_deserializer=summa__pb2.ForceMergeRequest.FromString,
            response_serializer=summa__pb2.ForceMergeResponse.SerializeToString,
        ),
        "Reorder": grpc.unary_unary_rpc_method_handler(
            servicer.Reorder,
            request_deserializer=summa__pb2.ReorderRequest.FromString,
            response_serializer=summa__pb2.ReorderResponse.SerializeToString,
        ),
        "DeleteIndex": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteIndex,
            request_deserializer=summa__pb2.DeleteIndexRequest.FromString,
            response_serializer=summa__pb2.DeleteIndexResponse.SerializeToString,
        ),
        "ListIndexes": grpc.unary_unary_rpc_method_handler(
            servicer.ListIndexes,
            request_deserializer=summa__pb2.ListIndexesRequest.FromString,
            response_serializer=summa__pb2.ListIndexesResponse.SerializeToString,
        ),
        "RetrainVectorIndex": grpc.unary_unary_rpc_method_handler(
            servicer.RetrainVectorIndex,
            request_deserializer=summa__pb2.RetrainVectorIndexRequest.FromString,
            response_serializer=summa__pb2.RetrainVectorIndexResponse.SerializeToString,
        ),
        "AlterVectorIndex": grpc.unary_unary_rpc_method_handler(
            servicer.AlterVectorIndex,
            request_deserializer=summa__pb2.AlterVectorIndexRequest.FromString,
            response_serializer=summa__pb2.AlterVectorIndexResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "summa.IndexService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("summa.IndexService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class IndexService:
    """Index service"""

    @staticmethod
    def CreateIndex(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/summa.IndexService/CreateIndex",
            summa__pb2.CreateIndexRequest.SerializeToString,
            summa__pb2.CreateIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def IndexDocuments(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            "/summa.IndexService/IndexDocuments",
            summa__pb2.IndexDocumentRequest.SerializeToString,
            summa__pb2.IndexDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def BatchIndexDocuments(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/summa.IndexService/BatchIndexDocuments",
            summa__pb2.BatchIndexDocumentsRequest.SerializeToString,
            summa__pb2.BatchIndexDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteDocuments(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/summa.IndexService/DeleteDocuments",
            summa__pb2.DeleteDocumentsRequest.SerializeToString,
            summa__pb2.DocumentMutationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpsertDocuments(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/summa.IndexService/UpsertDocuments",
            summa__pb2.UpsertDocumentsRequest.SerializeToString,
            summa__pb2.DocumentMutationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Commit(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/summa.IndexService/Commit",
            summa__pb2.CommitRequest.SerializeToString,
            summa__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ForceMerge(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/summa.IndexService/ForceMerge",
            summa__pb2.ForceMergeRequest.SerializeToString,
            summa__pb2.ForceMergeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Reorder(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/summa.IndexService/Reorder",
            summa__pb2.ReorderRequest.SerializeToString,
            summa__pb2.ReorderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteIndex(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/summa.IndexService/DeleteIndex",
            summa__pb2.DeleteIndexRequest.SerializeToString,
            summa__pb2.DeleteIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListIndexes(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/summa.IndexService/ListIndexes",
            summa__pb2.ListIndexesRequest.SerializeToString,
            summa__pb2.ListIndexesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RetrainVectorIndex(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/summa.IndexService/RetrainVectorIndex",
            summa__pb2.RetrainVectorIndexRequest.SerializeToString,
            summa__pb2.RetrainVectorIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AlterVectorIndex(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/summa.IndexService/AlterVectorIndex",
            summa__pb2.AlterVectorIndexRequest.SerializeToString,
            summa__pb2.AlterVectorIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
