[package]
name = "summa-bmp-query-bench"
version = "0.0.0"
edition = "2024"
[workspace]
[dependencies]
summa-core = { path = "../../../../../summa-core" }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
memmap2 = "0.9"
serde_json = "1"
libc = "0.2"
[profile.release]
lto = "thin"
codegen-units = 1
[features]
default = ["native"]
native = []
wasm = []
