apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: summa

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/part-of: summa

images:
  - name: ghcr.io/spacefrontiers/summa/summa-server
    newTag: latest
